#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_local_block", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_local_deadlock", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("ctl_cmd_stream_dout", 32, hls_in, 0, "ap_fifo", "fifo_data", 2),
	Port_Property("ctl_cmd_stream_empty_n", 1, hls_in, 0, "ap_fifo", "fifo_status", 2),
	Port_Property("ctl_cmd_stream_read", 1, hls_out, 0, "ap_fifo", "fifo_update", 2),
	Port_Property("a_baseaddr", 32, hls_out, 1, "ap_vld", "out_data", 1),
	Port_Property("a_baseaddr_ap_vld", 1, hls_out, 1, "ap_vld", "out_vld", 1),
	Port_Property("b_baseaddr", 32, hls_out, 2, "ap_vld", "out_data", 1),
	Port_Property("b_baseaddr_ap_vld", 1, hls_out, 2, "ap_vld", "out_vld", 1),
	Port_Property("c_baseaddr", 32, hls_out, 3, "ap_vld", "out_data", 1),
	Port_Property("c_baseaddr_ap_vld", 1, hls_out, 3, "ap_vld", "out_vld", 1),
	Port_Property("a_row", 32, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("a_row_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("a_col", 32, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("a_col_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("b_col", 32, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("b_col_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("work_id", 32, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("work_id_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "cl_box";
