// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cl_box_cl_box,hls_ip_2021_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu11p-flga2577-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.404000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=210,HLS_SYN_LUT=360,HLS_VERSION=2021_2}" *)

module cl_box (
        ap_local_block,
        ap_local_deadlock,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ctl_cmd_stream_dout,
        ctl_cmd_stream_empty_n,
        ctl_cmd_stream_read,
        a_baseaddr,
        a_baseaddr_ap_vld,
        b_baseaddr,
        b_baseaddr_ap_vld,
        c_baseaddr,
        c_baseaddr_ap_vld,
        a_row,
        a_row_ap_vld,
        a_col,
        a_col_ap_vld,
        b_col,
        b_col_ap_vld,
        work_id,
        work_id_ap_vld
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

output   ap_local_block;
output   ap_local_deadlock;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] ctl_cmd_stream_dout;
input   ctl_cmd_stream_empty_n;
output   ctl_cmd_stream_read;
output  [31:0] a_baseaddr;
output   a_baseaddr_ap_vld;
output  [31:0] b_baseaddr;
output   b_baseaddr_ap_vld;
output  [31:0] c_baseaddr;
output   c_baseaddr_ap_vld;
output  [31:0] a_row;
output   a_row_ap_vld;
output  [31:0] a_col;
output   a_col_ap_vld;
output  [31:0] b_col;
output   b_col_ap_vld;
output  [31:0] work_id;
output   work_id_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ctl_cmd_stream_read;
reg a_baseaddr_ap_vld;
reg b_baseaddr_ap_vld;
reg c_baseaddr_ap_vld;
reg a_row_ap_vld;
reg a_col_ap_vld;
reg b_col_ap_vld;
reg work_id_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ctl_cmd_stream_blk_n;
wire    ap_CS_fsm_state2;
reg   [31:0] tmp_reg_231;
wire   [31:0] add_ln22_fu_197_p2;
reg   [31:0] add_ln22_reg_236;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [2:0] cmd_array_address0;
reg    cmd_array_ce0;
reg    cmd_array_we0;
reg   [31:0] cmd_array_d0;
wire   [31:0] cmd_array_q0;
reg   [2:0] cmd_array_address1;
reg    cmd_array_ce1;
wire   [31:0] cmd_array_q1;
wire    grp_cl_box_Pipeline_1_fu_173_ap_start;
wire    grp_cl_box_Pipeline_1_fu_173_ap_done;
wire    grp_cl_box_Pipeline_1_fu_173_ap_idle;
wire    grp_cl_box_Pipeline_1_fu_173_ap_ready;
wire   [2:0] grp_cl_box_Pipeline_1_fu_173_cmd_array_address0;
wire    grp_cl_box_Pipeline_1_fu_173_cmd_array_ce0;
wire    grp_cl_box_Pipeline_1_fu_173_cmd_array_we0;
wire   [31:0] grp_cl_box_Pipeline_1_fu_173_cmd_array_d0;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_done;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_idle;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_ready;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ctl_cmd_stream_read;
wire   [2:0] grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_address0;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_ce0;
wire    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_we0;
wire   [31:0] grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_d0;
reg    grp_cl_box_Pipeline_1_fu_173_ap_start_reg;
reg    grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state8;
wire   [15:0] grp_fu_187_p4;
wire   [15:0] trunc_ln30_fu_203_p1;
wire   [15:0] trunc_ln32_fu_217_p1;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 grp_cl_box_Pipeline_1_fu_173_ap_start_reg = 1'b0;
#0 grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start_reg = 1'b0;
end

cl_box_cmd_array_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 5 ),
    .AddressWidth( 3 ))
cmd_array_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(cmd_array_address0),
    .ce0(cmd_array_ce0),
    .we0(cmd_array_we0),
    .d0(cmd_array_d0),
    .q0(cmd_array_q0),
    .address1(cmd_array_address1),
    .ce1(cmd_array_ce1),
    .q1(cmd_array_q1)
);

cl_box_cl_box_Pipeline_1 grp_cl_box_Pipeline_1_fu_173(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cl_box_Pipeline_1_fu_173_ap_start),
    .ap_done(grp_cl_box_Pipeline_1_fu_173_ap_done),
    .ap_idle(grp_cl_box_Pipeline_1_fu_173_ap_idle),
    .ap_ready(grp_cl_box_Pipeline_1_fu_173_ap_ready),
    .cmd_array_address0(grp_cl_box_Pipeline_1_fu_173_cmd_array_address0),
    .cmd_array_ce0(grp_cl_box_Pipeline_1_fu_173_cmd_array_ce0),
    .cmd_array_we0(grp_cl_box_Pipeline_1_fu_173_cmd_array_we0),
    .cmd_array_d0(grp_cl_box_Pipeline_1_fu_173_cmd_array_d0)
);

cl_box_cl_box_Pipeline_VITIS_LOOP_22_1 grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start),
    .ap_done(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_done),
    .ap_idle(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_idle),
    .ap_ready(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_ready),
    .ctl_cmd_stream_dout(ctl_cmd_stream_dout),
    .ctl_cmd_stream_empty_n(ctl_cmd_stream_empty_n),
    .ctl_cmd_stream_read(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ctl_cmd_stream_read),
    .add_ln22(add_ln22_reg_236),
    .cmd_array_address0(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_address0),
    .cmd_array_ce0(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_ce0),
    .cmd_array_we0(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_we0),
    .cmd_array_d0(grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cl_box_Pipeline_1_fu_173_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_cl_box_Pipeline_1_fu_173_ap_start_reg <= 1'b1;
        end else if ((grp_cl_box_Pipeline_1_fu_173_ap_ready == 1'b1)) begin
            grp_cl_box_Pipeline_1_fu_173_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_ready == 1'b1)) begin
            grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln22_reg_236 <= add_ln22_fu_197_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        tmp_reg_231 <= ctl_cmd_stream_dout;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        a_baseaddr_ap_vld = 1'b1;
    end else begin
        a_baseaddr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        a_col_ap_vld = 1'b1;
    end else begin
        a_col_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        a_row_ap_vld = 1'b1;
    end else begin
        a_row_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ctl_cmd_stream_empty_n == 1'b0) | (grp_cl_box_Pipeline_1_fu_173_ap_done == 1'b0))) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        b_baseaddr_ap_vld = 1'b1;
    end else begin
        b_baseaddr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        b_col_ap_vld = 1'b1;
    end else begin
        b_col_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        c_baseaddr_ap_vld = 1'b1;
    end else begin
        c_baseaddr_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        cmd_array_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        cmd_array_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        cmd_array_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        cmd_array_address0 = grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        cmd_array_address0 = grp_cl_box_Pipeline_1_fu_173_cmd_array_address0;
    end else begin
        cmd_array_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        cmd_array_address1 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        cmd_array_address1 = 64'd0;
    end else begin
        cmd_array_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        cmd_array_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        cmd_array_ce0 = grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        cmd_array_ce0 = grp_cl_box_Pipeline_1_fu_173_cmd_array_ce0;
    end else begin
        cmd_array_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        cmd_array_ce1 = 1'b1;
    end else begin
        cmd_array_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmd_array_d0 = grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        cmd_array_d0 = grp_cl_box_Pipeline_1_fu_173_cmd_array_d0;
    end else begin
        cmd_array_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmd_array_we0 = grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_cmd_array_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        cmd_array_we0 = grp_cl_box_Pipeline_1_fu_173_cmd_array_we0;
    end else begin
        cmd_array_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        ctl_cmd_stream_blk_n = ctl_cmd_stream_empty_n;
    end else begin
        ctl_cmd_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ctl_cmd_stream_empty_n == 1'b0) | (grp_cl_box_Pipeline_1_fu_173_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
        ctl_cmd_stream_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        ctl_cmd_stream_read = grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ctl_cmd_stream_read;
    end else begin
        ctl_cmd_stream_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        work_id_ap_vld = 1'b1;
    end else begin
        work_id_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if ((~((ctl_cmd_stream_empty_n == 1'b0) | (grp_cl_box_Pipeline_1_fu_173_ap_done == 1'b0)) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_baseaddr = cmd_array_q1;

assign a_col = trunc_ln30_fu_203_p1;

assign a_row = grp_fu_187_p4;

assign add_ln22_fu_197_p2 = ($signed(tmp_reg_231) + $signed(32'd4294967295));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_local_block = 1'b0;

assign ap_local_deadlock = 1'b0;

assign b_baseaddr = cmd_array_q0;

assign b_col = grp_fu_187_p4;

assign c_baseaddr = cmd_array_q1;

assign grp_cl_box_Pipeline_1_fu_173_ap_start = grp_cl_box_Pipeline_1_fu_173_ap_start_reg;

assign grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start = grp_cl_box_Pipeline_VITIS_LOOP_22_1_fu_179_ap_start_reg;

assign grp_fu_187_p4 = {{cmd_array_q0[31:16]}};

assign trunc_ln30_fu_203_p1 = cmd_array_q0[15:0];

assign trunc_ln32_fu_217_p1 = cmd_array_q0[15:0];

assign work_id = trunc_ln32_fu_217_p1;

endmodule //cl_box
